
name: Bank Backend Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Container Image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/bank-app-backend:${{ github.run_number }} .

      - name: Push Image to Docker Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/bank-app-backend:${{ github.run_number }}

      - name: Clean Up Docker Image Locally
        run: docker rmi ${{ secrets.REGISTRY_NAME }}/bank-app-backend:${{ github.run_number }}

  Continues-Deployment-gcp-k8s:
    runs-on: ubuntu-latest
    needs: Continues-Integration_build_and_push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Kubernetes Deployment File
        run: |
          sed -i "s+supportcloud160/bank-app-backend:.*+gtech2024/group3_bankapp:${{ github.run_number }}+g" deployment/deploy.yaml
          cat deployment/deploy.yaml

      - name: Authenticate to GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_JSON }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Google Cloud SDK
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates gnupg curl -y
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install google-cloud-cli -y
          sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin -y

      - name: Configure kubectl for GKE
        run: |
          gcloud container clusters get-credentials dev-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment/
          sleep 30
          kubectl get pods